apiVersion: apps/v1
kind: Deployment
metadata:
  name: credit-deployment
spec:
  selector:
    matchLabels:
      app: credit
  replicas: 1
  template:
    metadata:
      labels:
        app: credit
    spec:
      containers:
        - name: credit-pod
          image: zoomcamp-model:hw10
          resources:
            requests:
              memory: "128Mi"
              cpu: "200m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          ports:
            - containerPort: 9696
